# ~/.config/foot/foot.ini

#==FUENTES==#
font=monospace:size=11

#==CONFIGURACION==#
  # Padding de la Ventana
  pad=5x5

  # Tamaño de la Ventana
  [main]
  initial-window-size-pixels=880x480

  # Esconder el Raton mientras Escribes
  [mouse]
  hide-when-typing=yes

  # Estilo del Cursor
  [cursor]
  style=beam
  color=f5e0dc 161320
  blink=yes

#==PALETA-DE-COLORES-Y-TRANSPARENCIAS==#
  [colors-dark]
  alpha=0.85
  background=161320
  foreground=f5e0dc

  # Paleta ANSI de 16 Colores
  regular0=1e1e2e
  regular1=f38ba8
  regular2=a6e3a1
  regular3=f9e2af
  regular4=89b4fa
  regular5=cba6f7
  regular6=89dceb
  regular7=d9e0ee

  # Paleta ANSI de 16 Colores (Brillantes)
  bright0=575268
  bright1=f38ba8
  bright2=a6e3a1
  bright3=f9e2af
  bright4=89b4fa
  bright5=cba6f7
  bright6=fab387
  bright7=cdd6f4
